# Problema 2

En la carpeta encontrará adjuntos 21 documentos que tiene 100 fechas en la secuencia días-mes-año pero con distinto separador y distinto formato de mes, en algunos casos aparece un numero y en otros el nombre del mes en ingles, por ejemplo: Enero pueder aparecer como 1 o como Jan.

Utilice Python y expresiones regulares para encontrar el día, mes y año promedio total del los 21 archivos, los resultados deben ser un double.

In [59]:
from collections import Counter
from IPython.display import HTML
import pandas as pd
import re

In [21]:
days = list()
months = list()
years = list()

for i in range(1,22):
    file = open("./Datos/D"+str(i)+".txt", "r")
    for line in file:
        line = line.rstrip()
        pattern = "([12][0-9]|3[01]|0?[1-9])[/\.-]((?:1[0-2]|0?[1-9]|Jan|Feb|Ma[ry]|Apr|May|Ju[nl]|Aug|Sep|Oct|Nov|Dec))[/\.-](20\d{2})"
        match = re.search(pattern,line)
        if match:
            days.append(match.group(1))
            months.append(match.group(2))
            years.append(match.group(3))

### Promedio de día en documentos

In [79]:
days_df = pd.DataFrame.from_dict(Counter(days), orient='index', ).reset_index()
days_df.columns=["día","cantidad"]
days_df["promedio"] = days_df[["cantidad"]]/len(days)
HTML(days_df.sort_values(by=['día']).to_html(index=False))

### Promedio de mes en documentos

In [80]:
months_df = pd.DataFrame.from_dict(Counter(months), orient='index', ).reset_index()
months_df.columns=["mes","cantidad"]
months_df["promedio"] = months_df[["cantidad"]]/len(months)
HTML(months_df.sort_values(by=['mes']).to_html(index=False))

### Promedio de año en documentos

In [81]:
years_df = pd.DataFrame.from_dict(Counter(years), orient='index', ).reset_index()
years_df.columns=["año","cantidad"]
years_df["promedio"] = years_df[["cantidad"]]/len(years)
HTML(years_df.sort_values(by=['año']).to_html(index=False))